version: '3'

services:

  qualiexplore:
    ports:
      - 80:80
    
    image: robinkuri/i4q-editing-environment:latest

  json-server:
    ports:
      - 3000:3000
    image: robinkuri/quali-json-server:latest
  
  gql-mongo:
    ports:
      - "5000:5000"

    env_file:
      - .env

    image: hrabhijith/gql-mongo:quali